"""initial schema

Revision ID: 12c0a110fad2
Revises: 
Create Date: 2026-06-25 20:24:14.652936

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '12c0a110fad2'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('geocoding_cache',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('query', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('display_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('uncertain', sa.Boolean(), nullable=False),
    sa.Column('cached_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_geocoding_cache_query'), 'geocoding_cache', ['query'], unique=True)
    op.create_table('market',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('market_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('address', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('city', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('postal_code', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('country', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('geocode_uncertain', sa.Boolean(), nullable=False),
    sa.Column('program_text', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('original_text', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('source_url', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('source_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('hidden', sa.Boolean(), nullable=False),
    sa.Column('confidence_score', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name', 'start_date', 'source_url', name='uq_market_identity')
    )
    op.create_index(op.f('ix_market_city'), 'market', ['city'], unique=False)
    op.create_index(op.f('ix_market_hidden'), 'market', ['hidden'], unique=False)
    op.create_index(op.f('ix_market_name'), 'market', ['name'], unique=False)
    op.create_index(op.f('ix_market_source_url'), 'market', ['source_url'], unique=False)
    op.create_index(op.f('ix_market_start_date'), 'market', ['start_date'], unique=False)
    op.create_table('source',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('base_url', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('adapter_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('crawl_interval_hours', sa.Integer(), nullable=False),
    sa.Column('last_crawled_at', sa.DateTime(), nullable=True),
    sa.Column('last_success_at', sa.DateTime(), nullable=True),
    sa.Column('last_error', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_source_name'), 'source', ['name'], unique=True)
    op.create_table('user_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('home_latitude', sa.Float(), nullable=True),
    sa.Column('home_longitude', sa.Float(), nullable=True),
    sa.Column('home_label', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('default_radius_km', sa.Float(), nullable=False),
    sa.Column('default_month_offset_start', sa.Integer(), nullable=False),
    sa.Column('default_month_offset_end', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('crawl_job',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source_id', sa.Integer(), nullable=False),
    sa.Column('source_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.Column('events_discovered', sa.Integer(), nullable=False),
    sa.Column('events_inserted', sa.Integer(), nullable=False),
    sa.Column('events_updated', sa.Integer(), nullable=False),
    sa.Column('error_message', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['source_id'], ['source.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_crawl_job_source_id'), 'crawl_job', ['source_id'], unique=False)
    op.create_index(op.f('ix_crawl_job_status'), 'crawl_job', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_crawl_job_status'), table_name='crawl_job')
    op.drop_index(op.f('ix_crawl_job_source_id'), table_name='crawl_job')
    op.drop_table('crawl_job')
    op.drop_table('user_settings')
    op.drop_index(op.f('ix_source_name'), table_name='source')
    op.drop_table('source')
    op.drop_index(op.f('ix_market_start_date'), table_name='market')
    op.drop_index(op.f('ix_market_source_url'), table_name='market')
    op.drop_index(op.f('ix_market_name'), table_name='market')
    op.drop_index(op.f('ix_market_hidden'), table_name='market')
    op.drop_index(op.f('ix_market_city'), table_name='market')
    op.drop_table('market')
    op.drop_index(op.f('ix_geocoding_cache_query'), table_name='geocoding_cache')
    op.drop_table('geocoding_cache')
    # ### end Alembic commands ###
